### PR TITLE
add sysmacros patch for cramfs 1.1 and squashfs 4.2 for major/minor/makedev

### PR DESCRIPTION
**Pull request by limes007**
does not build without this in my environment since commit https://github.com/Duckbox-Developers/buildsystem-ddt/commit/a566ded06ffcd7d955bf017b4e020f61a4073791

### CODE REVIEW

**Comment by BPanther** [comment]
I build many images and all build without problems. Please write the box and options you are using (make.sh parameter).

BTW: GST is not longer testet and not really used anymore if you use this one.

**Comment by limes007** [comment]
I use an empty Kubuntu 19 and first execute prepare-for-bs.sh and then using config

> BOXARCH=sh4
BOXTYPE=spark7162
KERNEL_STM=p0217
OPTIMIZATIONS=size
MEDIAFW=buildinplayer
IMAGE=neutrino
FLAVOUR=neutrino-mp-ddt
EXTERNAL_LCD=none 

and then

> make printenv
make crosstool
make bootstrap

make bootstrap fails, because 'minor' is not defined

**Comment by BPanther** [comment]
Strange, works here with Ubuntu LTS 18.04.2 without problems. Maybe a problem with KUbuntu.

And why do you use single commands and not just make neutrino?

But, added. Try it now...

**Comment by limes007** [comment]
Thanks, works now.

Is was quite a journey for me the first time I build neutrino. I have read many things and somewhere I read, that these three steps are needed to build neutrino. As it works, I use it still in this way...

Unfortunately, my build image was be damaged. So I have to setup a new one. And now I run into different problems. But now it is one less. ;-)

**Comment by BPanther** [comment]
Thanks for your response. ;)

**Pull request closed without merging**
